---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
library("dplyr")
library("ggplot2")
library("ggthemes")
library("ggmosaic")
library("plotly")
library("lintr")
library("stringr")
library("data.table")
source("scripts/chart_one.R")
source("scripts/chart_two.R")
source("scripts/summary.R")
data <- read.csv("data/intro-survey.csv", stringsAsFactors = FALSE)
data_list <- summarizing_data(data)
data <- data_list$modified_table
```

## R Markdown

From the survey data of Info 201 class this quarter, we see that there are `r data_list$total_students` 
in our Info201 class, with `r data_list$no_exp_r`% of students who
have never used R language before and `r data_list$no_exp_git`% of students who have never used git before.
There are also `r data_list$no_exp_coding`% of students with no programming experience.

In this report, we will investigate more about students' experience from the survey data using two plots.


#plot 1: coding experience by class standing

This first plot shows the coding experience of different class standings, from which we see
that Sophomores are the largest group of students in this class. For every class standing, 
the number of experienced programmers (with lots or moderate coding experience) is more
than half of the total number. Hence it would not be very surprising if students generally
do a great job in this class. Sophomore has the largest group of students with no programming
experience, which is very interesting.

`r chart_one_function(data_list$sorted_data, "class_standing", "number_of_students", "coding_experience")`

#plot 2: git usage by coding experience

This second plot shows the git usage by coding experience.The width of each bar is proportional
to the number of people with the corresponding coding experience. From this plot we see that most 
students have never used git before. Even more than half of people with moderate coding experience
have never used git. Although most students with lots of programming experience have used git in
the past, students at this coding experience level are only a small portion of the whole class.

`r chart_two_function(data)`
